name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        path: 'garrysmod_common'
        ref: x86-64-support-sourcesdk
    - name: Install Premake
      run: |
         curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip -o premake.zip
         tar -xf premake.zip
    - name: Generate Project
      run: |
        ./premake5.exe --gmcommon=garrysmod_common vs2019
    - name: Build
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x86
      run: msbuild eightbit.sln -t:rebuild -verbosity:diag -property:Configuration=Release
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_windows.dll
        path: projects/windows/vs2019/x86/ReleaseWithSymbols/gmsv_eightbit_win32.dll
    - name: Build 64
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
      run: msbuild eightbit.sln -t:rebuild -verbosity:diag -property:Configuration=Release
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_win64.dll
        path: projects/windows/vs2019/x86_64/ReleaseWithSymbols/gmsv_eightbit_win64.dll
